easy_admin:
    site_name: Fitness App
    design:
        menu:
            - {route: 'homepage', label: 'Back to the website', icon: 'home'}
            - {entity: 'User', label: 'Users', icon: 'user'}
            - {entity: 'Goal', label: 'Goals', icon: 'bullseye'}
            - {entity: 'Workout', label: 'Workouts', icon: 'swimmer'}
            - {entity: 'Exercise', label: 'Exercises', icon: 'walking'}
            - {entity: 'DifficultyLevel', label: 'Difficulty Levels', icon: 'dumbbell'}
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - name
                    - { property: 'gender', type: 'choice', type_options: { choices: { '': '', 'Male': 'm', 'Female': 'f' }} }
                    - weight
                    - height
                    - age
                    - goal
                    - workout
        Goal:
            class: App\Entity\Goal
            form:
                fields:
                    - name
                    - description
                    - workouts

        Workout:
            class: App\Entity\Workout
            form:
                fields:
                    - name
                    - { property: 'image', type: 'file_upload' }
                    - { property: 'gender', type: 'choice', type_options: { choices: { '': '', 'Male': 'm', 'Female': 'f' }} }
                    - goal
                    - difficulty_level
                    - exercises

        Exercise:
            class: App\Entity\Exercise
            form:
                fields:
                    - name
                    - { property: 'male_image', type: 'file_upload' }
                    - { property: 'female_image', type: 'file_upload' }
                    - { property: 'description', type: 'text_editor' }
                    - workouts

        DifficultyLevel:
            class: App\Entity\DifficultyLevel
            form:
                fields:
                    - name
                    - difficulty_order